Adjust makefiles to compile sources on 64 bit VS 2017 c++14 environment.
A few 'error C2664' instances related to two methods had to be fixed.

The first line comments in 'v3r0_vs2017_c++<standard>_build.Nmakefile's
are changed to say 'VS 2017 Developer Command Prompt' which is closer to
the name advertised on the Start button menu.